version: '3'

services:
  web:
    # image: php:7.2-apache
    build: ./dockerfiles/php
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./log/apache2:/var/log/apache2
    container_name: myweb

      

